name: Build

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Run linters
        run: pnpm lint
      - name: Run unit tests
        run: pnpm test:unit
      - name: Run e2e tests
        run: pnpm test:e2e
      - name: Move output of Omega Star
        run: |
          mkdir -p out
          mv apps/omega-star/out out/omega-star
          mv out apps/omega-star/
      - name: Run Lighthouse tests on Omega Star
        run: |
          cd apps/omega-star
          lhci autorun --config=lighthouse.config.js
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Move output of website
        run: |
          mkdir -p out
          mv apps/website/out out${{ steps.pages.outputs.base_path }}
          mv out apps/website/
      - name: Run Lighthouse tests on website
        run: |
          cd apps/website
          lhci autorun --config=lighthouse.config.js
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Upload website
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: apps/website/out${{ steps.pages.outputs.base_path }}
          retention-days: 1
      - name: Upload e2e test reports
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: e2e-reports
          path: |
            apps/omega-star/e2e-report/
            apps/omega-star/e2e-results/
            apps/website/e2e-report/
            apps/website/e2e-results/
          retention-days: 7
